blank_issues_enabled: true
contact_links:
  - name: â­ Sponsor ZBXLLD
    url: https://github.com/sponsors/skarllot
    about: Help the continued development.
  - name: ğŸ’¬ Ask on Github Discussions
    url: https://github.com/skarllot/zbxlld/discussions
    about: The best place for asking general purpose questions.
